import { i18n } from '../src/core/i18n.js';

describe('I18nEngine', () => {
  beforeEach(() => {
    // Reset to reliable state
    i18n.setLocale('en');
  });

  test('should return english translation by default', () => {
    const text = i18n.t('agents.generatedBy');
    expect(text).toBe('Generated by Architect v8.1');
  });

  test('should change locale to pt-BR', () => {
    i18n.setLocale('pt-BR');
    const text = i18n.t('agents.generatedBy');
    expect(text).toBe('Gerado por Architect v8.1');
  });

  test('should format strings using params', () => {
    const text = i18n.t('agents.backend.title', { lang: 'TYPESCRIPT' });
    expect(text).toBe('🔧 TYPESCRIPT BACKEND DEVELOPER');
  });

  test('should respond with error string for missing keys', () => {
    const text = i18n.t('invalid.key.path');
    expect(text).toBe('[Missing translation: invalid.key.path]');
  });

  test('should fallback to en if present in en but missing in pt-BR', () => {
    // Force a runtime scenario
    const engine: any = i18n;
    engine.currentLocale = 'pt-BR';
    const dict = engine.getDict();
    
    // Temporarily delete a key
    const backup = dict.agents.generatedBy;
    delete dict.agents.generatedBy;

    const text = i18n.t('agents.generatedBy');
    // should have fallen back to EN
    expect(text).toBe('Generated by Architect v8.1');

    // Restore
    dict.agents.generatedBy = backup;
  });
});
