import { AppTranslation } from './pt-BR.js';

export const en: AppTranslation = {
  // === CLI ===
  cli: {
    phases: {
      scan: { label: 'FILE SCANNER', verb: 'Scanning filesystem' },
      dependencies: { label: 'DEPENDENCY MAPPER', verb: 'Mapping import graph' },
      layers: { label: 'LAYER DETECTOR', verb: 'Classifying architecture' },
      antipatterns: { label: 'PATTERN ANALYZER', verb: 'Detecting anti-patterns' },
      scoring: { label: 'QUALITY ENGINE', verb: 'Computing quality metrics' },
      normalize: { label: 'PATH NORMALIZER', verb: 'Normalizing paths' },
      summarize: { label: 'AI SUMMARIZER', verb: 'Generating project summary' }
    },
    results: {
      score: 'ARCHITECTURE SCORE',
      completedIn: 'Completed in',
      files: 'files',
      lines: 'lines',
      anitpatterns: 'anti-patterns',
      steps: 'steps',
      agents: 'agents'
    }
  },

  // === AGONTS OUTPUTS ===
  agents: {
    generatedBy: 'Generated by Architect v3.1',
    backend: {
      description: '{lang} Backend Developer — APIs, services, business logic',
      title: '🔧 {lang} BACKEND DEVELOPER',
      specialistIn: 'Backend specialist in {fw} for {projectName}',
      stack: 'Stack',
      language: 'Language',
      framework: 'Framework',
      architecture: 'Architecture',
      test: 'Test Framework',
      packageManager: 'Package Manager',
      currentScore: 'Current Score',
      domainContext: 'Domain & Business Context',
      principles: 'Principles (SOLID + Clean Architecture)',
      modules: 'Project Modules',
      projectStructure: 'Project Structure (Detected)',
      implementationRules: 'Implementation Rules',
      implementationRulesBody: `□ Controller MUST NEVER contain business logic (routing only)
□ Service MUST NEVER access Request/Response directly
□ Entity MUST NEVER be exposed directly in API (use DTO)
□ Input validation in DTO / Guard / Pipe
□ Errors thrown with clear messages and correct HTTP status
□ Structured logging (never console.log)
□ Unit tests for every service method
□ Integration tests for every endpoint
□ Coverage ≥ {coverage}%`,
      afterImplementation: 'After Backend Implementation',
      afterImplementationBody: `> **MANDATORY: Generate Integration Document before proceeding to frontend/app.**

Document must contain:
- All created/modified endpoints
- Request and response payloads (with examples)
- Error codes and messages
- Business rules applied
- Required headers (auth, pagination, etc.)`
    },
    frontend: {
      description: '{fw} Frontend Developer — Components, UX, state management',
      title: '🎨 {fw} FRONTEND DEVELOPER',
      specialistIn: 'Frontend specialist in {fw} for {projectName}',
      prerequisites: 'Prerequisites for Implementation',
      prerequisitesBody: `╔══════════════════════════════════════════════╗
║  BEFORE writing any UI component:            ║
║                                              ║
║  □ MOCKUP approved by human                  ║
║  □ Integration Document available            ║
║  □ User stories with acceptance criteria     ║
║  □ BDD scenarios written                     ║
╚══════════════════════════════════════════════╝`,
      implementationRules: 'Implementation Rules',
      implementationRulesBody: `□ Component follows approved MOCKUP (do not invent UI)
□ ALL UI states implemented:
  - ✅ Data present (normal state)
  - 📭 Empty state
  - ⏳ Loading state (skeleton)
  - ❌ Error state (with clear message)
□ Business logic in services (NEVER in the component)
□ Proper state management (no prop drilling)
□ Forms with client-side validation
□ Responsive layout (mobile + desktop)
□ Basic accessibility (labels, aria, contrast)
□ Lazy loading where applicable
□ Coverage ≥ {coverage}%`
    },
    security: {
      description: 'Security Auditor — Threat analysis, compliance, vulnerability scanning',
      title: '🛡️ SECURITY AUDITOR',
      analysisFor: 'Security Analysis for {projectName}',
      checklist: 'OWASP Top 10 Checklist',
      checklistBody: `□ A01: Broken Access Control — RBAC implemented?
□ A02: Cryptographic Failures — Sensitive data encrypted?
□ A03: Injection — Inputs sanitized? Parameterized queries?
□ A04: Insecure Design — Threat modeling performed?
□ A05: Security Misconfiguration — Secure headers, CORS?
□ A06: Vulnerable Components — Dependencies updated?
□ A07: Auth Failures — Brute-force protected? Session managed?
□ A08: Software Integrity — Supply chain verified?
□ A09: Logging Failures — Audit logs for sensitive actions?
□ A10: SSRF — Server-side requests validated?`,
      whenToActivate: 'When To Activate',
      whenToActivateBody: `- Any feature handling: auth, personal data, payments
- New public APIs
- External system integrations
- Infrastructure/Ops changes`,
      expectedOutput: 'Expected Output',
      expectedOutputBody: `1. Findings list with severity levels (CRITICAL/HIGH/MEDIUM/LOW)
2. Mitigation recommendations
3. Threat model (if applicable)`
    },
    qa: {
      description: 'QA Test Engineer — Test planning, BDD/TDD, coverage analysis',
      title: '🧪 QA TEST ENGINEER',
      qualityFor: 'Test Quality mapping for {projectName}',
      nonNegotiable: 'Non-Negotiable Targets',
      nonNegotiableBody: `╔══════════════════════════════════════════╗
║  Minimum Coverage: {coverage}%                ║
║  No tests = no delivery, no completion   ║
║  NON-NEGOTIABLE.                         ║
╚══════════════════════════════════════════╝`,
      pyramid: 'Testing Pyramid',
      pyramidBody: `         ╱╲
        ╱ E2E╲         → Few, slow, high value
       ╱──────╲
      ╱Integration╲    → Medium, validate integration
     ╱──────────────╲
    ╱   Unit Tests    ╲ → Many, fast, cheap
   ╱════════════════════╲`,
      process: 'Testing Process',
      processBody: `1. **BDD first** — Gherkin scenarios before code
2. **TDD** — RED → GREEN → REFACTOR
3. **Coverage** — verify after each implementation
4. **Regression** — ALL previous tests must pass
5. **Review** — tests are reviewed alongside the code`,
      refactoringRoadmap: 'Refactoring Roadmap'
    },
    techDebt: {
      description: 'Tech Debt Controller — Technical debt backlog and score enforcement',
      title: '📊 TECH DEBT CONTROLLER',
      controlFor: 'Tech debt tracking for {projectName}',
      currentState: 'Current State',
      stateTable: `| Metric | Value |
|---------|-------|
| Score | {score}/100 |
| Target | {target}/100 |
| Anti-patterns | {antiPatterns} |
| Pending Refactors | {refactoringSteps} |
| Estimated Gain | +{improvement} points |`,
      refactoringRoadmap: 'Refactoring Roadmap',
      scoreTargets: 'Score Targets',
      scoreTargetsBody: `Current Score:          {score}/100
Short-Term Target:      {targetShort}/100
Mid-Term Target:        {targetMedium}/100
Minimum Acceptable:     {threshold}/100`,
      rules: 'Enforcement Rules',
      rulesBody: `□ Score MUST NEVER regress after a PR
□ Minimum allowed: {threshold}/100
□ Critical: resolve within 1 sprint
□ High: resolve within 2 sprints
□ Medium: add to technical backlog
□ Verify using: architect score ./src`
    },
    codeReview: {
      description: 'Code Review Checklist — Mandatory review points',
      title: '🔍 CODE REVIEW CHECKLIST — {projectName}',
      mandatoryRule: '**Every PR must be verified against this checklist.**',
      mandatory: 'Mandatory',
      mandatoryBody: `□ Code compiles without errors
□ All tests pass
□ Coverage ≥ {coverage}%
□ Lint passes without errors
□ No hardcoded secrets
□ Score has not regressed`,
      functional: 'Functional',
      functionalBody: `□ Meets acceptance criteria
□ Edge cases handled
□ Errors handled appropriately
□ Exisiting features not broken`,
      quality: 'Quality',
      qualityBody: `□ Code readable without explanatory comments
□ Naming is descriptive and consistent
□ Functions are small and focused
□ No code duplication (DRY)
□ Complex logic is isolated and tested
□ No large commented out code blocks`,
      domainReviewItems: 'Domain-Specific Review Items: {domain}',
      domainRules: {
        fintech: `□ Are transactions idempotent?
□ Complete audit of all operations?
□ No sensitive data exposed in logs?
□ Monetary values use Decimal (no floats)?
□ PCI-DSS compliance verified?`,
        healthtech: `□ GDPR/LGPD compliance verified?
□ Sensitive data encrypted at rest?
□ Access audited and logged?
□ Anonymization implemented correctly?
□ 2FA for sensitive operations?`,
        ecommerce: `□ Cart is idempotent?
□ Inventory updated correctly (race conditions)?
□ Prices validated (no client-side manipulation)?
□ Coupons/discounts applied correctly?
□ Fraud detection implemented?`,
        default: `□ Critical business workflow intact?
□ Rollback is safe?
□ Concurrency handled?
□ Final state is consistent?`
      },
      stackReviewItems: 'Language-Specific Checklist: {stack}',
      stackRules: {
        ts: `□ \`strict: true\` in tsconfig (no unjustified 'any')?
□ Circular imports?
□ Async/await handled (no unhandled promises)?
□ Memory leaks (EventListeners unsubscribed)?
□ Console.log/debugger removed?`,
        python: `□ Type hints on all public functions?
□ Docstrings formatted (Google or NumPy style)?
□ No mutable default arguments?
□ Context managers used for resources?
□ F-strings instead of % or .format()?
□ No \`eval()\` or \`exec()\`?`,
        go: `□ Errors handled (not ignored with _)?
□ Defer for cleanup?
□ Goroutines with context?
□ Race conditions tested?
□ Timeouts implemented?`,
        dart: `□ Null-safety (! avoided)?
□ Widgets have keys in lists?
□ BuildContext accessed only in build?
□ Listeners unsubscribed?
□ Images/assets load lazily?`,
        default: `□ Code follows project standards?
□ Dependencies updated?
□ No compiler/linter warnings?`
      },
      integrationReviewItems: 'Integration Review Items',
      integrationRulesBody: `□ Endpoint handles all expected status codes?
□ Input payload validation?
{auth}
{validation}
□ Response follows the documented contract?
□ Errors return clear messages?
□ Rate limiting applied?
□ Structured logging?`
    }
  },

  // === DYNAMIC BLOCKS ===
  dynamic: {
    compliance: {
      title: 'Detected Compliance Requirements',
      reason: 'Reason',
      mandatoryChecks: 'Mandatory Checks'
    },
    integrations: {
      title: 'Integration Security',
      threats: 'Threats',
      types: {
        payment: 'PCI-DSS, sensitive data encryption, tokenization',
        auth: 'MFA, session hijacking, credential stuffing',
        api: 'Rate limiting, API key rotation, required HTTPS',
        database: 'SQL Injection, Encryption at rest, Backups',
        government: 'Regulatory compliance, audit trails, data retention',
        default: 'Input/output validation, rate limiting'
      }
    },
    domainThreats: {
      title: 'Domain-Specific Threats: {domain}',
      fintech: `- **Data Manipulation:** Transaction audits, checksums, encryption
- **Unauthorized Access:** MFA on privileged accounts, IP whitelist
- **Compliance:** PCI-DSS, LGPD/GDPR, SOX
- **Fraud:** Anomaly detection, rate limiting`,
      healthtech: `- **Data Leakage:** End-to-end encryption, anonymization
- **HIPAA/GDPR:** Audit trails, explicit consent
- **Integrity:** Digital signatures, blockchain if applicable
- **Access:** Granular RBAC, 2FA for sensitive data`,
      ecommerce: `- **Payment Fraud:** CVV validation, 3D Secure
- **Data Theft:** SSL/TLS, PCI-DSS, encryption at rest
- **DoS:** Rate limiting, CAPTCHA, WAF
- **Auth:** MFA, session timeout`,
      default: `- **Confidentiality:** Data encrypted in transit and at rest
- **Integrity:** Input validation, checksums
- **Availability:** Backup, disaster recovery, monitoring
- **Auditing:** Logging sensitive actions, retention policy`
    },
    qaDomain: {
      title: 'Domain-Specific Test Scenarios: {domain}',
      fintech: `### Business Tests
- Create transaction with valid amounts
- Reject transaction above limit
- Process refund correctly
- Audit logging of all transactions
- Validate balance after multiple operations

### Security Tests
- Do not expose card data in logs
- Validate PCI-DSS compliance
- Test fraud detection`,
      healthtech: `### Business Tests
- Create patient record with GDPR compliance
- Validate consent before sharing data
- Anonymize data correctly
- Respect right to be forgotten
- Audit access to sensitive data

### Security Tests
- E2E encryption at rest
- Validate 2FA for critical data
- Test data retention`,
      ecommerce: `### Business Tests
- Create cart with multiple products
- Apply discount/coupon correctly
- Process payment with 3DS validation
- Update inventory after sale
- Generate order with correct status

### Security Tests
- Do not expose card data
- Validate rate limiting on checkout
- Test fraud protection`,
      default: `### Business Tests
- Main flow (happy path)
- Edge cases and boundaries
- Concurrency (race conditions)
- Rollback after error
- Idempotency

### Security Tests
- Invalid/malicious inputs
- Unauthorized access
- Rate limiting
- Proper logging`
    }
  }
};
